import { ClerkProvider } from "@clerk/nextjs";
import { checkRole } from "@/app/lib/roles";
import { redirect } from "next/navigation";
import "../globals.css";
import SideNav from "@/app/ui/admin/dashboard/sidenav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (!checkRole("admin")) {
    redirect("/");
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
              <SideNav />
            </div>
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
